import 'bootstrap-icons/font/bootstrap-icons.css';

import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css"; // your custom CSS

import { Suspense } from 'react';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function checkout({ children }) {
  return (
   <Suspense>

        {children}
   </Suspense>
       
     
  );
}
